name: Online Bookstore CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  security:
    uses: ./.github/workflows/security.yml
    needs: [test]

  quality:
    uses: ./.github/workflows/code-quality.yml
    needs: [test]

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [test, security, quality]

  notify:
    uses: ./.github/workflows/notify.yml
    needs: [test, security, quality]
